In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("C:\\Users\\edwin\\OneDrive\\Desktop\\development_journey\\20.Machine Learning\\regression\\mall_customers\\Mall_Customers.csv.xls")

In [4]:
df.head()

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [5]:
df.shape

(200, 5)

In [6]:
df.isnull().sum()

CustomerID                0
Genre                     0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [7]:
df[df.duplicated]

Empty DataFrame
Columns: [CustomerID, Genre, Age, Annual Income (k$), Spending Score (1-100)]
Index: []

In [8]:
df.drop(columns="CustomerID",inplace=True)

In [9]:
X=df.iloc[:,:-1]

In [10]:
Y=df.iloc[:,-1]

In [11]:
X.head()

    Genre  Age  Annual Income (k$)
0    Male   19                  15
1    Male   21                  15
2  Female   20                  16
3  Female   23                  16
4  Female   31                  17

In [12]:
Y.head()

0    39
1    81
2     6
3    77
4    40
Name: Spending Score (1-100), dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

X["Genre"]=pd.DataFrame(le.fit_transform(X["Genre"]))

In [14]:
Y=pd.DataFrame(le.fit_transform(Y))

In [15]:
X.head()

   Genre  Age  Annual Income (k$)
0      1   19                  15
1      1   21                  15
2      0   20                  16
3      0   23                  16
4      0   31                  17

In [16]:
Y.head()

    0
0  30
1  67
2   4
3  64
4  31

In [17]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [18]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()

X_train=pd.DataFrame(scaler.fit_transform(X_train))
X_test=pd.DataFrame(scaler.transform(X_test))

In [19]:
from sklearn.neighbors import KNeighborsRegressor

knn=KNeighborsRegressor(n_neighbors=7)

knn.fit(X_train,Y_train)

KNeighborsRegressor(n_neighbors=7)

In [20]:
Y_pred_knn=knn.predict(X_test)

In [21]:
from sklearn.linear_model import LinearRegression

lr=LinearRegression()

lr.fit(X_train,Y_train)

LinearRegression()

In [22]:
Y_pred_lr=lr.predict(X_test)

In [23]:
from sklearn.metrics import r2_score

print("r2_score",r2_score(Y_test,Y_pred_lr)*100)

r2_score 12.847356465003635

In [24]:
from sklearn.metrics import r2_score

print("r2_score",r2_score(Y_test,Y_pred_knn)*100)

r2_score 27.091120391995528

In [25]:
from sklearn.tree import DecisionTreeRegressor

dt=DecisionTreeRegressor()

dt.fit(X_train,Y_train)

DecisionTreeRegressor()

In [26]:
Y_pred_dt=dt.predict(X_test)

In [27]:
from sklearn.metrics import r2_score

print("r2_score",r2_score(Y_test,Y_pred_dt))

r2_score -0.46815436504823893

In [28]:
from sklearn.ensemble import AdaBoostRegressor

ada=AdaBoostRegressor()

ada.fit(X_train,Y_train)

C:\Users\edwin\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

AdaBoostRegressor()

In [29]:
Y_pred_ada=ada.predict(X_test)

In [30]:
from sklearn.metrics import r2_score

print("r2_score",r2_score(Y_test,Y_pred_ada))

r2_score 0.22364964660336928

In [31]:
from sklearn.ensemble import GradientBoostingRegressor

gb=GradientBoostingRegressor()

gb.fit(X_train,Y_train)

C:\Users\edwin\AppData\Roaming\Python\Python313\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

GradientBoostingRegressor()

In [32]:
Y_pred_gb=gb.predict(X_test)

In [33]:
from sklearn.metrics import r2_score

print("r2_score",r2_score(Y_test,Y_pred_gb))

r2_score 0.10279807533167229