In [130]:
import pandas as pd
import nltk
import numpy as np
import matplotlib.pyplot as plt

In [131]:
df = pd.read_csv(r"C:\Users\edwin\OneDrive\Desktop\development_journey\21.NLP_works\online_product_review\reviews.csv.xls",header=None)

In [132]:
df.columns = ["id","source","sentiment","review"]
df.head()

   id    source   sentiment             review
0   1  Flipkart    positive      good product#
1   2  Flipkart    negative  not worth buying😅
2   3    Amazon  irrelevant          hello hai
3   4    Amazon    positive  excellent service
4   5  Flipkart    negative        bad quality

### display positive reviews

In [133]:
df[df["sentiment"] == "positive"]

     id    source sentiment                       review
0     1  Flipkart  positive                good product#
3     4    Amazon  positive            excellent service
5     6    Amazon  positive                fast delivery
6     7  Flipkart  positive              value for money
8     9    Myntra  positive              nice collection
10   11  Flipkart  positive          very useful product
12   13    Meesho  positive             affordable price
14   15      Ajio  positive             loved the design
16   17    Amazon  positive           highly recommended
18   19    Myntra  positive          good fabric quality
20   21      Ajio  positive              perfect fitting
22   23  Flipkart  positive            works as expected
24   25    Amazon  positive           awesome experience
26   27      Ajio  positive              stylish product
28   29    Amazon  positive              great packaging
30   31      Ajio  positive                 good quality
31   32    Meesho  positive      satisfied with purchase
33   34    Amazon  positive            easy installation
34   35    Myntra  positive          comfortable to wear
36   37    Meesho  positive              worth the price
38   39  Flipkart  positive        excellent performance
40   41      Ajio  positive             beautiful design
42   43    Meesho  positive                 nice product
44   45    Myntra  positive                looks premium
46   47    Amazon  positive             really impressed
48   49  Flipkart  positive          super fast shipping
50   51    Myntra  positive              amazing comfort
52   53    Meesho  positive           good for daily use
54   55  Flipkart  positive                  easy to use
56   57      Ajio  positive            worth every penny
58   59    Amazon  positive           best purchase ever
60   61    Myntra  positive                   good value
62   63    Meesho  positive            excellent quality
64   65  Flipkart  positive            good battery life
65   66    Myntra  positive                 nice fitting
68   69    Amazon  positive        recommend to everyone
70   71    Myntra  positive  lightweight and comfortable
71   72      Ajio  positive              awesome product
73   74    Amazon  positive               quick delivery
75   76    Myntra  positive           excellent purchase
77   78    Meesho  positive           loved this product
79   80  Flipkart  positive               good packaging
81   82      Ajio  positive                good material
83   84    Amazon  positive              works perfectly
85   86    Myntra  positive                  great style
87   88    Meesho  positive          happy with purchase
89   90  Flipkart  positive              excellent value
91   92      Ajio  positive              nice appearance
93   94    Amazon  positive                very reliable
95   96    Myntra  positive           comfortable fabric
96   97      Ajio  positive                great fitting
99  100  Flipkart  positive         fantastic experience

### display negative reviews

In [134]:
df[df["sentiment"] == "negative"]

    id    source sentiment                    review
1    2  Flipkart  negative         not worth buying😅
4    5  Flipkart  negative               bad quality
7    8    Amazon  negative     received damaged item
9   10    Myntra  negative             size mismatch
13  14    Meesho  negative            poor packaging
15  16      Ajio  negative       color faded quickly
17  18  Flipkart  negative             late delivery
21  22    Amazon  negative            waste of money
23  24    Myntra  negative      returned the product
25  26    Meesho  negative            cheap material
29  30    Myntra  negative            poor stitching
32  33  Flipkart  negative   product stopped working
35  36      Ajio  negative      wrong size delivered
37  38    Amazon  negative  customer support was bad
41  42    Amazon  negative         very disappointed
43  44  Flipkart  negative          not as described
45  46      Ajio  negative           average quality
47  48    Meesho  negative              item missing
51  52      Ajio  negative     poor customer service
53  54    Amazon  negative      package arrived late
55  56    Myntra  negative           fabric not good
57  58    Meesho  negative   broken product received
61  62      Ajio  negative      delivery was delayed
63  64    Amazon  negative             not satisfied
67  68    Meesho  negative         very poor quality
69  70  Flipkart  negative            defective item
72  73    Meesho  negative            bad experience
74  75  Flipkart  negative          item was damaged
76  77      Ajio  negative               not durable
80  81    Myntra  negative                size issue
82  83    Meesho  negative            poor finishing
84  85  Flipkart  negative      returned immediately
86  87      Ajio  negative   quality could be better
88  89    Amazon  negative           not recommended
92  93    Meesho  negative      wrong item delivered
94  95  Flipkart  negative          poor performance
98  99    Amazon  negative               bad product

### display negative reviews and positive reviews

In [135]:
df = df[df["sentiment"].isin(["positive","negative"])]

In [136]:
df

     id    source sentiment                review
0     1  Flipkart  positive         good product#
1     2  Flipkart  negative     not worth buying😅
3     4    Amazon  positive     excellent service
4     5  Flipkart  negative           bad quality
5     6    Amazon  positive         fast delivery
..  ...       ...       ...                   ...
94   95  Flipkart  negative      poor performance
95   96    Myntra  positive    comfortable fabric
96   97      Ajio  positive         great fitting
98   99    Amazon  negative           bad product
99  100  Flipkart  positive  fantastic experience

[89 rows x 4 columns]

### implement positive as 1 and negative as -1

In [137]:
df["sentiment"] = df["sentiment"].map({"positive":1,"negative":-1,"neutral":0})

In [138]:
df

     id    source  sentiment                review
0     1  Flipkart          1         good product#
1     2  Flipkart         -1     not worth buying😅
3     4    Amazon          1     excellent service
4     5  Flipkart         -1           bad quality
5     6    Amazon          1         fast delivery
..  ...       ...        ...                   ...
94   95  Flipkart         -1      poor performance
95   96    Myntra          1    comfortable fabric
96   97      Ajio          1         great fitting
98   99    Amazon         -1           bad product
99  100  Flipkart          1  fantastic experience

[89 rows x 4 columns]

###convert source to lowercase

In [139]:
df["source"] = df["source"].apply(lambda row:row.lower())

In [140]:
df.head()

   id    source  sentiment             review
0   1  flipkart          1      good product#
1   2  flipkart         -1  not worth buying😅
3   4    amazon          1  excellent service
4   5  flipkart         -1        bad quality
5   6    amazon          1      fast delivery

In [141]:
df["review"] = df["review"].apply(lambda row:row.lower())

In [142]:
df

     id    source  sentiment                review
0     1  flipkart          1         good product#
1     2  flipkart         -1     not worth buying😅
3     4    amazon          1     excellent service
4     5  flipkart         -1           bad quality
5     6    amazon          1         fast delivery
..  ...       ...        ...                   ...
94   95  flipkart         -1      poor performance
95   96    myntra          1    comfortable fabric
96   97      ajio          1         great fitting
98   99    amazon         -1           bad product
99  100  flipkart          1  fantastic experience

[89 rows x 4 columns]

### remove special characters

In [143]:
import re
df["review"] = df["review"].str.replace("[^A-Za-z0-9 ]","",regex=True)

In [144]:
df.head()

   id    source  sentiment             review
0   1  flipkart          1       good product
1   2  flipkart         -1   not worth buying
3   4    amazon          1  excellent service
4   5  flipkart         -1        bad quality
5   6    amazon          1      fast delivery

In [145]:
from nltk.corpus import stopwords
# nltk.download('stopwords')
# nltk.download('punkt_tab')
sw = stopwords.words("english")

### remove stopwords from reviews

In [146]:
df["review"] = df["review"].apply(lambda row: [t for t in nltk.word_tokenize(row) if t not in sw]).apply(lambda t: " ".join(t))

In [148]:
df.head()

   id    source  sentiment             review
0   1  flipkart          1       good product
1   2  flipkart         -1       worth buying
3   4    amazon          1  excellent service
4   5  flipkart         -1        bad quality
5   6    amazon          1      fast delivery