In [80]:
import pandas as pd
import nltk
import numpy as np
import matplotlib.pyplot as plt

In [81]:
df = pd.read_csv(r"C:\Users\edwin\OneDrive\Desktop\development_journey\21.NLP_works\twitter\twitter_training.csv.xls",header=None)

In [82]:
df

,0,1,2,3
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
...,...,...,...,...
74677,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74678,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74679,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74680,9200,Nvidia,Positive,Just realized between the windows partition of...
74681,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [83]:
df.columns = ["id","company","sentiment","review"]
df.head()

,id,company,sentiment,review
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

In [84]:
df["sentiment"].value_counts()

sentiment
Negative      22542
Positive      20832
Neutral       18318
Irrelevant    12990
Name: count, dtype: int64

In [85]:
df.drop_duplicates(keep="first",inplace=True)

In [86]:
df.isnull().sum()

id             0
company        0
sentiment      0
review       326
dtype: int64

In [87]:
df["sentiment"].value_counts()

sentiment
Negative      21787
Positive      19811
Neutral       17800
Irrelevant    12584
Name: count, dtype: int64

In [88]:
df.dropna(subset=['review'],inplace=True)

In [89]:
df.isnull().sum()

id           0
company      0
sentiment    0
review       0
dtype: int64

In [90]:
df["sentiment"] = df["sentiment"].map({"Positive":1,"Negative":-1,"Neutral":0})

In [91]:
df

,id,company,sentiment,review
0,2401,Borderlands,1.0,im getting on borderlands and i will murder yo...
1,2401,Borderlands,1.0,I am coming to the borders and I will kill you...
2,2401,Borderlands,1.0,im getting on borderlands and i will kill you ...
3,2401,Borderlands,1.0,im coming on borderlands and i will murder you...
4,2401,Borderlands,1.0,im getting on borderlands 2 and i will murder ...
...,...,...,...,...
74677,9200,Nvidia,1.0,Just realized that the Windows partition of my...
74678,9200,Nvidia,1.0,Just realized that my Mac window partition is ...
74679,9200,Nvidia,1.0,Just realized the windows partition of my Mac ...
74680,9200,Nvidia,1.0,Just realized between the windows partition of...
74681,9200,Nvidia,1.0,Just like the windows partition of my Mac is l...