#### load required module

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
!pip list

Package                      Version
---------------------------- -----------
absl-py                      2.3.1
altair                       6.0.0
annotated-types              0.7.0
anyio                        4.10.0
app                          0.0.1
arabic-reshaper              3.0.0
asgiref                      3.9.1
asn1crypto                   1.5.1
asttokens                    3.0.1
attrs                        26.1.0
beautifulsoup4               4.14.2
blinker                      1.9.0
cachetools                   6.2.1
certifi                      2025.8.3
cffi                         2.0.0
charset-normalizer           3.4.3
click                        8.2.1
colorama                     0.4.6
comm                         0.2.3
contourpy                    1.3.3
crispy-bootstrap4            2025.6
crispy-bootstrap5            2024.10
cryptography                 46.0.3
cssselect2                   0.8.0
cycler                       0.12.1
debugpy                      1.8.20
decorator                    5.2.1
distro                       1.9.0
Django                       5.2.4
django-crispy-forms          2.3
django-extensions            3.2.3
django-multiselectfield      0.1.13
django-widget-tweaks         1.5.0
docopt                       0.6.2
et_xmlfile                   2.0.0
executing                    2.2.1
fastapi                      0.116.1
ffmpeg-python                0.2.0
filelock                     3.18.0
Flask                        3.1.2
flatbuffers                  25.9.23
fonttools                    4.60.1
freetype-py                  2.5.1
fsspec                       2025.7.0
future                       1.0.0
gitdb                        4.0.12
GitPython                    3.1.46
google-ai-generativelanguage 0.6.15
google-api-core              2.28.1
google-api-python-client     2.187.0
google-auth                  2.43.0
google-auth-httplib2         0.2.1
google-generativeai          0.8.5
googleapis-common-protos     1.72.0
grpcio                       1.76.0
grpcio-status                1.71.2
gunicorn                     23.0.0
h11                          0.16.0
html5lib                     1.1
httpcore                     1.0.9
httplib2                     0.31.0
httpx                        0.28.1
huggingface-hub              0.34.4
idna                         3.10
ImageIO                      2.37.2
imageio-ffmpeg               0.6.0
ipykernel                    7.2.0
ipython                      9.13.0
ipython_pygments_lexers      1.1.1
itsdangerous                 2.2.0
jedi                         0.20.0
Jinja2                       3.1.6
jiter                        0.11.1
joblib                       1.5.3
jsonschema                   4.26.0
jsonschema-specifications    2025.9.1
jupyter_client               8.8.0
jupyter_core                 5.9.1
kiwisolver                   1.4.9
llvmlite                     0.46.0
lxml                         6.0.2
MarkupSafe                   3.0.2
matplotlib                   3.10.7
matplotlib-inline            0.2.2
mediapipe                    0.10.31
more-itertools               10.8.0
moviepy                      2.2.1
mpmath                       1.3.0
mysql-connector-python       9.6.0
mysqlclient                  2.2.7
narwhals                     2.18.1
nest-asyncio                 1.6.0
networkx                     3.5
num2words                    0.5.14
numba                        0.63.1
numpy                        2.2.6
openai                       2.7.1
openai-whisper               20250625
opencv-python                4.12.0.88
openpyxl                     3.1.5
oscrypto                     1.3.0
packaging                    25.0
pandas                       2.3.3
parso                        0.8.7
pillow                       11.3.0
pip                          24.3.1
platformdirs                 4.9.6
polars                       1.37.1
polars-runtime-32            1.37.1
proglog                      0.1.12
prompt_toolkit               3.0.52
proto-plus                   1.26.1
protobuf                     5.29.5
psutil                       7.2.1
pure_eval                    0.2.3
pyarrow                      23.0.1
pyasn1                       0.6.1
pyasn1_modules               0.4.2
pycairo                      1.29.0
pycparser                    2.23
pydantic                     2.11.7
pydantic_core                2.33.2
pydeck                       0.9.1
Pygments                     2.20.0
pyHanko                      0.32.0
pyhanko-certvalidator        0.29.0
pyparsing                    3.2.5
pypdf                        6.4.0
python-bidi                  0.6.7
python-dateutil              2.9.0.post0
python-docx                  1.2.0
python-dotenv                1.2.1
python-multipart             0.0.20
pytz                         2025.2
PyYAML                       6.0.2
pyzmq                        27.1.0
referencing                  0.37.0
regex                        2025.7.34
reportlab                    4.4.5
requests                     2.32.4
rlPyCairo                    0.4.0
rpds-py                      0.30.0
rsa                          4.9.1
safetensors                  0.6.2
scikit-learn                 1.8.0
scipy                        1.17.0
seaborn                      0.13.2
setuptools                   80.9.0
six                          1.17.0
smmap                        5.0.3
sniffio                      1.3.1
sounddevice                  0.5.3
soupsieve                    2.8
sqlparse                     0.5.3
stack-data                   0.6.3
starlette                    0.47.2
streamlit                    1.56.0
svglib                       1.6.0
sympy                        1.14.0
tenacity                     9.1.4
threadpoolctl                3.6.0
tiktoken                     0.12.0
tinycss2                     1.5.1
tokenizers                   0.21.4
toml                         0.10.2
torch                        2.9.1
torchvision                  0.24.1
tornado                      6.5.5
tqdm                         4.67.1
traitlets                    5.15.0
transformers                 4.55.0
typing_extensions            4.14.1
typing-inspection            0.4.1
tzdata                       2025.2
tzlocal                      5.3.1
ultralytics                  8.4.6
ultralytics-thop             2.0.18
uritemplate                  4.2.0
uritools                     5.0.0
urllib3                      2.5.0
uvicorn                      0.35.0
watchdog                     6.0.0
wcwidth                      0.7.0
webencodings                 0.5.1
Werkzeug                     3.1.5
xhtml2pdf                    0.2.17
xlsxwriter                   3.2.9
yt-dlp                       2025.12.8

In [4]:
df = pd.read_csv("C:\\Users\\edwin\\OneDrive\\Desktop\\development_journey\\20.Machine Learning\\student_case_study\\knn_student_dataset.csv.xls")
df

       City  StudyHours  Attendance  Assignments Result
0     Delhi         2.0        30.0          1.0   Fail
1    Mumbai         3.0        45.0          2.0   Fail
2   Chennai         5.0        60.0          3.0   Pass
3     Delhi         NaN        50.0          2.0   Fail
4       NaN         6.0         NaN          4.0   Pass
5    Mumbai         7.0        75.0          NaN   Pass
6   Chennai         8.0        85.0          5.0   Pass
7     Delhi         1.0        25.0          1.0   Fail
8    Mumbai         4.0        55.0          3.0   Fail
9   Chennai         6.0        65.0          4.0   Pass
10    Delhi         7.0        80.0          5.0   Pass
11   Mumbai         NaN        70.0          4.0   Pass
12      NaN         5.0        58.0          3.0   Pass
13  Chennai         9.0         NaN          5.0   Pass
14    Delhi         2.0        35.0          NaN   Fail

In [5]:
df.shape

(15, 5)

In [6]:
df.columns

Index(['City', 'StudyHours', 'Attendance', 'Assignments', 'Result'], dtype='object')

In [7]:
df.head()

      City  StudyHours  Attendance  Assignments Result
0    Delhi         2.0        30.0          1.0   Fail
1   Mumbai         3.0        45.0          2.0   Fail
2  Chennai         5.0        60.0          3.0   Pass
3    Delhi         NaN        50.0          2.0   Fail
4      NaN         6.0         NaN          4.0   Pass

In [8]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [9]:
X.head()

      City  StudyHours  Attendance  Assignments
0    Delhi         2.0        30.0          1.0
1   Mumbai         3.0        45.0          2.0
2  Chennai         5.0        60.0          3.0
3    Delhi         NaN        50.0          2.0
4      NaN         6.0         NaN          4.0

In [10]:
Y.head()

0    Fail
1    Fail
2    Pass
3    Fail
4    Pass
Name: Result, dtype: object

In [11]:
df.isnull().sum()

City           2
StudyHours     2
Attendance     2
Assignments    2
Result         0
dtype: int64

In [12]:
X["City"] = X["City"].fillna(X["City"].mode()[0])

In [13]:
X.isnull().sum()

City           0
StudyHours     2
Attendance     2
Assignments    2
dtype: int64

In [14]:
X['City']

0       Delhi
1      Mumbai
2     Chennai
3       Delhi
4       Delhi
5      Mumbai
6     Chennai
7       Delhi
8      Mumbai
9     Chennai
10      Delhi
11     Mumbai
12      Delhi
13    Chennai
14      Delhi
Name: City, dtype: object

In [15]:
! pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\edwin\appdata\roaming\python\python313\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\edwin\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\edwin\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\edwin\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\edwin\appdata\roaming\python\python313\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
X.isnull().sum()

City           0
StudyHours     2
Attendance     2
Assignments    2
dtype: int64

In [17]:
num_cols = ["StudyHours","Attendance","Assignments"]

In [18]:
from sklearn.impute import SimpleImputer

In [19]:
impute = SimpleImputer(missing_values=np.nan,strategy="mean")
X[num_cols] = impute.fit_transform(X[num_cols])

In [20]:
X.isnull().sum()

City           0
StudyHours     0
Attendance     0
Assignments    0
dtype: int64

In [21]:
X

       City  StudyHours  Attendance  Assignments
0     Delhi         2.0   30.000000     1.000000
1    Mumbai         3.0   45.000000     2.000000
2   Chennai         5.0   60.000000     3.000000
3     Delhi         5.0   50.000000     2.000000
4     Delhi         6.0   56.384615     4.000000
5    Mumbai         7.0   75.000000     3.230769
6   Chennai         8.0   85.000000     5.000000
7     Delhi         1.0   25.000000     1.000000
8    Mumbai         4.0   55.000000     3.000000
9   Chennai         6.0   65.000000     4.000000
10    Delhi         7.0   80.000000     5.000000
11   Mumbai         5.0   70.000000     4.000000
12    Delhi         5.0   58.000000     3.000000
13  Chennai         9.0   56.384615     5.000000
14    Delhi         2.0   35.000000     3.230769

In [22]:
X[X.duplicated()]

Empty DataFrame
Columns: [City, StudyHours, Attendance, Assignments]
Index: []

In [23]:
df[df.duplicated()]

Empty DataFrame
Columns: [City, StudyHours, Attendance, Assignments, Result]
Index: []

In [24]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [25]:
ct = ColumnTransformer([("encoder",OneHotEncoder(),[0])],remainder="passthrough")
X=pd.DataFrame(ct.fit_transform(X))

In [26]:
X.head()

     0    1    2    3          4    5
0  0.0  1.0  0.0  2.0  30.000000  1.0
1  0.0  0.0  1.0  3.0  45.000000  2.0
2  1.0  0.0  0.0  5.0  60.000000  3.0
3  0.0  1.0  0.0  5.0  50.000000  2.0
4  0.0  1.0  0.0  6.0  56.384615  4.0

In [27]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

Y=pd.DataFrame(le.fit_transform(Y))

In [28]:
Y.head()

   0
0  0
1  0
2  1
3  0
4  1

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test =  train_test_split(X,Y,test_size=0.2,random_state=42)

In [30]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = pd.DataFrame(scaler.fit_transform(X_train))
X_test = pd.DataFrame(scaler.transform(X_test))

In [31]:
X_train.head()

     0    1    2      3         4         5
0  1.0  0.0  0.0  1.000  0.523077  1.000000
1  0.0  0.0  1.0  0.750  0.833333  0.557692
2  0.0  0.0  1.0  0.375  0.500000  0.500000
3  1.0  0.0  0.0  0.500  0.583333  0.500000
4  0.0  0.0  1.0  0.250  0.333333  0.250000

In [32]:
X_test.head()

     0    1    2      3         4     5
0  1.0  0.0  0.0  0.625  0.666667  0.75
1  0.0  0.0  1.0  0.500  0.750000  0.75
2  0.0  1.0  0.0  0.125  0.083333  0.00