In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [64]:
df = pd.read_csv("C:\\Users\\edwin\\OneDrive\\Desktop\\development_journey\\20.Machine Learning\\sales_case_study\\sales_data.csv.xls")
df

,ProductCategory,Price,Stock,Discount,CustomerRating,DeliveryDays,ReturnRequested,SalesStatus
0,Electronics,25000.0,15.0,10.0,4.5,3.0,No,High
1,Fashion,1200.0,40.0,20.0,3.8,5.0,Yes,Medium
2,Groceries,500.0,100.0,5.0,4.2,1.0,No,High
3,Electronics,NaN,10.0,15.0,4.0,4.0,No,Medium
4,NaN,1500.0,NaN,25.0,3.5,6.0,Yes,Low
...,...,...,...,...,...,...,...,...
73,Groceries,570.0,93.0,5.0,4.3,2.0,No,Medium
74,Electronics,29500.0,10.0,11.0,NaN,4.0,No,Medium
75,Fashion,2300.0,21.0,13.0,4.2,5.0,No,Medium
76,Furniture,47000.0,1.0,32.0,5.0,14.0,No,High
77,Groceries,NaN,102.0,4.0,4.1,1.0,No,High

In [65]:
df.shape

(78, 8)

In [66]:
df.columns

Index(['ProductCategory', 'Price', 'Stock', 'Discount', 'CustomerRating',
       'DeliveryDays', 'ReturnRequested', 'SalesStatus'],
      dtype='object')

In [67]:
X = df.iloc[:,:-1]
X

,ProductCategory,Price,Stock,Discount,CustomerRating,DeliveryDays,ReturnRequested
0,Electronics,25000.0,15.0,10.0,4.5,3.0,No
1,Fashion,1200.0,40.0,20.0,3.8,5.0,Yes
2,Groceries,500.0,100.0,5.0,4.2,1.0,No
3,Electronics,NaN,10.0,15.0,4.0,4.0,No
4,NaN,1500.0,NaN,25.0,3.5,6.0,Yes
...,...,...,...,...,...,...,...
73,Groceries,570.0,93.0,5.0,4.3,2.0,No
74,Electronics,29500.0,10.0,11.0,NaN,4.0,No
75,Fashion,2300.0,21.0,13.0,4.2,5.0,No
76,Furniture,47000.0,1.0,32.0,5.0,14.0,No
77,Groceries,NaN,102.0,4.0,4.1,1.0,No

In [68]:
Y = df.iloc[:,-1]
Y

0       High
1     Medium
2       High
3     Medium
4        Low
       ...
73    Medium
74    Medium
75    Medium
76      High
77      High
Name: SalesStatus, Length: 78, dtype: object

In [69]:
X.head()

,ProductCategory,Price,Stock,Discount,CustomerRating,DeliveryDays,ReturnRequested
0,Electronics,25000.0,15.0,10.0,4.5,3.0,No
1,Fashion,1200.0,40.0,20.0,3.8,5.0,Yes
2,Groceries,500.0,100.0,5.0,4.2,1.0,No
3,Electronics,NaN,10.0,15.0,4.0,4.0,No
4,NaN,1500.0,NaN,25.0,3.5,6.0,Yes

In [70]:
Y.head()

0      High
1    Medium
2      High
3    Medium
4       Low
Name: SalesStatus, dtype: object

In [71]:
X.isnull().sum()

ProductCategory    3
Price              8
Stock              3
Discount           4
CustomerRating     4
DeliveryDays       4
ReturnRequested    2
dtype: int64

In [72]:
cat_cols = ["ProductCategory","ReturnRequested"]
from sklearn.impute import SimpleImputer

impute = SimpleImputer(missing_values=np.nan,strategy="most_frequent")
X[cat_cols] = impute.fit_transform(X[cat_cols])

In [73]:
X.isnull().sum()

ProductCategory    0
Price              8
Stock              3
Discount           4
CustomerRating     4
DeliveryDays       4
ReturnRequested    0
dtype: int64

In [74]:
num_cols = ["Price","Stock","Discount","CustomerRating","DeliveryDays"]

In [75]:
from sklearn.impute import SimpleImputer

In [76]:
impute = SimpleImputer(missing_values=np.nan,strategy="mean")
X[num_cols] = impute.fit_transform(X[num_cols])

In [77]:
X.isnull().sum()

ProductCategory    0
Price              0
Stock              0
Discount           0
CustomerRating     0
DeliveryDays       0
ReturnRequested    0
dtype: int64

In [78]:
X.head()

,ProductCategory,Price,Stock,Discount,CustomerRating,DeliveryDays,ReturnRequested
0,Electronics,25000.0,15.000000,10.0,4.5,3.0,No
1,Fashion,1200.0,40.000000,20.0,3.8,5.0,Yes
2,Groceries,500.0,100.000000,5.0,4.2,1.0,No
3,Electronics,19454.0,10.000000,15.0,4.0,4.0,No
4,Electronics,1500.0,36.146667,25.0,3.5,6.0,Yes

In [79]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

X["ReturnRequested"]=pd.DataFrame(le.fit_transform(X["ReturnRequested"]))

In [80]:
X.isnull().sum()

ProductCategory    0
Price              0
Stock              0
Discount           0
CustomerRating     0
DeliveryDays       0
ReturnRequested    0
dtype: int64

In [82]:
X.head()

,ProductCategory,Price,Stock,Discount,CustomerRating,DeliveryDays,ReturnRequested
0,Electronics,25000.0,15.000000,10.0,4.5,3.0,0
1,Fashion,1200.0,40.000000,20.0,3.8,5.0,1
2,Groceries,500.0,100.000000,5.0,4.2,1.0,0
3,Electronics,19454.0,10.000000,15.0,4.0,4.0,0
4,Electronics,1500.0,36.146667,25.0,3.5,6.0,1

In [83]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [84]:
ct = ColumnTransformer([("encoder",OneHotEncoder(),[0])],remainder="passthrough")
X=pd.DataFrame(ct.fit_transform(X))

In [85]:
X.head()

     0    1    2    3        4           5     6    7    8    9
0  1.0  0.0  0.0  0.0  25000.0   15.000000  10.0  4.5  3.0  0.0
1  0.0  1.0  0.0  0.0   1200.0   40.000000  20.0  3.8  5.0  1.0
2  0.0  0.0  0.0  1.0    500.0  100.000000   5.0  4.2  1.0  0.0
3  1.0  0.0  0.0  0.0  19454.0   10.000000  15.0  4.0  4.0  0.0
4  1.0  0.0  0.0  0.0   1500.0   36.146667  25.0  3.5  6.0  1.0

In [86]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

Y=pd.DataFrame(le.fit_transform(Y))

In [87]:
Y.head()

   0
0  0
1  2
2  0
3  2
4  1

In [88]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test =  train_test_split(X,Y,test_size=0.2,random_state=42)

In [89]:
X_train.shape

(62, 10)

In [91]:
X_test.shape

(16, 10)

In [90]:
df.shape

(78, 8)

In [92]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = pd.DataFrame(scaler.fit_transform(X_train))
X_test = pd.DataFrame(scaler.transform(X_test))

In [93]:
X_train.head()

     0    1    2    3         4         5         6       7         8    9
0  0.0  1.0  0.0  0.0  0.021776  0.341085  0.696970  0.3125  0.428571  1.0
1  1.0  0.0  0.0  0.0  0.782245  0.023256  0.151515  0.8125  0.142857  0.0
2  0.0  0.0  1.0  0.0  0.463987  0.023256  0.242424  0.7500  0.571429  0.0
3  0.0  0.0  1.0  0.0  0.581240  0.031008  0.360770  0.8125  0.500000  0.0
4  0.0  1.0  0.0  0.0  0.320838  0.209302  0.393939  0.0625  0.357143  1.0

In [94]:
X_test.head()

     0    1    2    3         4         5         6       7         8    9
0  0.0  0.0  0.0  1.0  0.004188  0.651163  0.090909  0.3750  0.071429  0.0
1  1.0  0.0  0.0  0.0  0.413735  0.108527  0.242424  0.6875  0.142857  0.0
2  1.0  0.0  0.0  0.0  1.201005  0.000000  0.181818  0.9375  0.000000  0.0
3  1.0  0.0  0.0  0.0  0.865997  0.015504  0.545455  0.8750  0.642857  1.0
4  0.0  1.0  0.0  0.0  0.025126  0.186047  0.393939  0.3750  0.291506  0.0